### PR TITLE
Upgrade to FAKE 5

### PR DESCRIPTION
**Pull request by NinoFloris**
Upgrades build chain to use FAKE 5, not sure if `appveyor-build.cmd` will work in one go but we'll see!

### CODE REVIEW

**Comment by simontaite** [comment]
Hi Nino,
Thanks for the PR. Would you be able to keep appveyor-build.cmd as build.cmd?
Having one command that will build and test the solution can be very helpful

Similarly, fake.sh is a good addition, I particularly like the check for installing the current .NET Core if not already installed.
Maybe we could keep the name of build.sh and default the args to "build" for `dotnet fake $@`?
I'm not entirely sure of the capabilities of `dotnet fake`, can it handle multiple parameters? I'm wondering if there was a reason for `$@` over `$1`

Otherwise it builds correctly and runs all tests on both Windows and Linux.
I can check later on MacOS but I don't see any issues there if it builds correctly on Linux

**Comment by NinoFloris** [comment]
Sure that's possible it'll just be an alias for `dotnet fake build` for now.

Most of the structure (fake.sh and the absence of build.cmd/sh) is pulled from the FAKE repo itself and the sample https://github.com/FakeBuild/fake-bootstrap/tree/paket_clitool so at least it should be pretty idiomatic.

Let me know if you'd like build.cmd/sh back then I'll push that asap.

**Comment by simontaite** [comment]
If you can bring back the build.cmd/sh I'd appreciate it, thanks

**Comment by simontaite** [comment]
Perfect, thank you for the work on this

**Pull request merged**
